site_name: {{ cookiecutter.project_name }}
site_url: https://{{ cookiecutter.repo_username }}.{{ cookiecutter.repo_type }}.io/{{ cookiecutter.project_slug }}
repo_url: https://{{ cookiecutter.repo_type }}.com/{{ cookiecutter.repo_username }}/{{ cookiecutter.project_slug }}
repo_name: {{ cookiecutter.repo_username }}/{{ cookiecutter.project_slug }}
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: readthedocs
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - {{ cookiecutter.pkg_name }}
extra:
  social:
    - icon: fontawesome/brands/{{ cookiecutter.repo_type }}
      link: https://{{ cookiecutter.repo_type }}.com/{{ cookiecutter.repo_username }}/{{ cookiecutter.project_slug }}
      name: {{ cookiecutter.repo_type | capitalize }}
