site_name: Cookiecutter Pypackage with Poetyr and mkdocs
site_url: https://mattkatz.github.io/cc-pypa-poetry-mkdocs/
repo_url: https://github.com/mattkatz/cc-pypa-poetry-mkdocs
repo_name: mattkatz/cc-pypa-poetry-mkdocs
nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Console script: console_script_setup.md
  - Release checklist: pypi_release_checklist.md
  - FAQ: faq.md
  - History: history.md

theme:
  name: readthedocs
  language: en
  #logo: assets/logo.png
  palette:
      scheme: preference
      primary: indigo
      accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mattkatz
      name: Github
